import json
F=[
["Working","High","Pressing Enter (or the 'Go'/search key on a phone keyboard) in the postcode box skips all eight household questions and jumps straight to the results, with no household.",
 "Anyone who presses Enter after typing their postcode — on a phone that is the natural thing to do. Found by Dennis (keyboard-only).",
 "Reproduced every time on desktop and on a phone-sized screen (SW9 7BD).",
 "Make Enter in the postcode box do the same as 'Next' (go to question 2) instead of submitting the whole form."],
["Working","High","If someone types their postcode before the page has finished loading, the postcode stays in the box but 'Next' stays greyed out for good, with no message. Clearing and retyping it fixes it.",
 "Grace and Callum (slow mobile data), plus Jordan, Leo, Stan and Nadia on the first pass. Most likely on phones and poor signal.",
 "Controlled test on a slow connection: typed at 0s, 0.3s and 1.5s after the box appeared → stuck; typed at 4s → fine. Also happened once on a normal connection.",
 "Read the box's current value when the page becomes interactive (or don't grey out Next, and check the postcode on click)."],
["Working","Medium","A postcode that doesn't exist (e.g. XX1 1XX, or 'PA3l 8NB' with a letter l) is accepted on the first screen. The person answers all nine steps, then gets sent back to the home page with 'We can't find that postcode' and all their answers are lost.",
 "Nadia (typo). Anyone who mistypes.",
 "End-to-end runs with XX1 1XX and PA3l 8NB.",
 "Check the postcode when 'Next' is pressed on step 1 and show the error there. If it fails at the end, keep the answers."],
["Working","Medium","Typing just the first half of a postcode (e.g. NG31) greys out 'Next' with no explanation of what's wrong.",
 "Beatrice. Also likely for people who don't want to give their full postcode.",
 "Run on NG31.",
 "Show a hint like 'Enter your full postcode, e.g. NG31 6SF', or accept a district and let people pick their ward."],
["Working","Medium","Where candidates haven't been confirmed yet, the page says '0 candidates are standing here' (Penn Hill, Mid Argyll) or '1 candidate is standing here … 1 candidates for one seat' (Beechwood & Heath). Democracy Club marks all three as not yet confirmed, so these read as if nobody (or one person) is standing.",
 "Harriet (Poole), Nadia (Mid Argyll), Olu (Runcorn).",
 "Candidate counts matched Democracy Club on all 17 ballots. These three are the only ones DC has not locked, and they have no statement of persons nominated.",
 "When candidates aren't locked, say 'Candidates not confirmed yet — the official list is published on [date]'. Fix the '1 candidates' plural."],
["Money figures","Medium","The money box ignores visa/asylum and student status. Fatima (Graduate visa, looking for work) is shown +£9,686 Universal Credit. Amara (single full-time university student) is shown +£4,186. GOV.UK says Graduate visa holders can't claim most benefits ('public funds'), and Universal Credit is on the public funds list. Asylum seekers can't claim Universal Credit either. Single full-time students without a child or partner generally can't claim it. The assumptions list doesn't mention either limit.",
 "Fatima, Amara (Holborn). Would affect every visa or student household on any ballot with a money box.",
 "GOV.UK 'Universal Credit: eligibility' (student exceptions), 'Graduate visa' (can't apply for most benefits/public funds) and 'Public funds' guidance (Universal Credit listed). Page's own 'Assumptions' text says 'Universal Credit and Child Benefit are claimed where there is entitlement' with no visa/student rule.",
 "Set Universal Credit to zero (or hide the money box with a sourced explanation) when visa = yes or the person is a full-time student without a child or partner. Add both to the assumptions list."],
["Money figures","Low","The first line, 'Earnings, and other income, taxes and benefits the model counts', shows −£180 for Fatima, who has no income, and £3,372 for Grace, who isn't working. It's a balancing figure, so the label reads like earnings when it isn't.",
 "Fatima, Grace.",
 "Page text: 'The first line is worked out as the net income, plus the tax and National Insurance paid, less the two benefits listed'.",
 "Split out real earnings and label the remainder 'Other taxes and benefits (net)', or hide it when it's small or negative."],
["Working","Low","A 16-year-old in England (Kezia, Lambeth council by-election) goes through the whole journey without being told she can't vote in this election. She could in Scotland or Wales.",
 "Kezia.",
 "Searched her result, candidate and 'at stake' pages for any age or eligibility wording: none found.",
 "When age is 16–17 and the ballot is in England (or a UK Parliament ballot), add one line: 'You can't vote in this one yet, but you can register now at 16…'."],
["Working","Low","Skipping just one question (income) means the candidates page shows the empty 'Describe a household' form instead of 'This household: …', even though six answers were given. The topics shown first still use them.",
 "Kezia.",
 "Candidates page text for Kezia: '6 of 7 chosen', no household summary.",
 "Show the summary for whatever was answered."],
["Working","Low","Now and then, 'See my election' did nothing on the first click. A second click worked.",
 "Not seen in the 30 main runs. Seen twice in about 45 extra runs.",
 "Intermittent; couldn't pin down the cause.",
 "Worth a look: disable the button and show 'Finding your election…' once clicked, so a slow response doesn't look like nothing happened."],
["Working","Low","A Guernsey postcode (GY1 1AA) is treated as UK. It's told it gets UK local and general elections, and the map is centred on 0,0 (off West Africa).",
 "Edge case, no persona.",
 "Run on GY1 1AA → /place?pc=GY1&loc=0.000,0.000.",
 "Detect Channel Islands and Isle of Man postcodes (GY, JE, IM) and say the site covers UK elections only."],
["Working","Low","In Northern Ireland the council row says 'Belfast · Central ward not listed' — no councillors are shown.",
 "Siobhan.",
 "No-election page for BT7 1NN.",
 "Check the NI councillor data (NI councils elect by District Electoral Area, not ward)."],
["Accessibility","High","After each answer in the questions, keyboard focus drops to the page itself and nothing is announced (there is no live region). A screen-reader user may not realise the next question has appeared, and could be taken back to the top of the page.",
 "Yusuf (blind, screen reader). Also affects keyboard users, though Tab still carried on from the right place in Chromium.",
 "After every one of the seven answers, the focused element was <body>. No aria-live, role=status or role=alert regions on /start. Needs a check with real NVDA/VoiceOver.",
 "After each step, move focus to the new question's heading (tabindex=-1), or announce 'Step 3 of 9: Adults in the household' in a polite live region."],
["Accessibility","Medium","On phones and at 200% zoom, the money table scrolls sideways, but the scrolling box can't be reached with the keyboard.",
 "Amara, Tomasz, Fatima, Grace (mobile), Margaret (200% zoom).",
 "axe-core: 'scrollable-region-focusable' on section[aria-labelledby=current-law] > .scroll.",
 "Add tabindex=0 and an aria-label to the scrolling box, or stack the table on narrow screens."],
["Accessibility","Low","A few links on the candidates page are under 24 px tall.",
 "Yusuf's run (desktop).",
 "axe-core 'target-size' (WCAG 2.2): 3 elements, e.g. a candidate jump link at 22.8 px.",
 "Add a little padding to those links."],
["Fairness of experience","Medium","What people get depends heavily on where they live. Holborn has 266 sourced positions from 14 of 15 candidates plus a money box. The 16 council ballots tested have 20 positions between them (about 1.25 each), 6 have none at all (2 because candidates aren't confirmed yet), and none has a money box. So every Scottish and Welsh tester, and everyone outside Camden, mostly saw 'Nothing published yet'.",
 "Everyone except the Holborn testers (and Rahul, whose postcode had no election).",
 "Counts from each ballot page (Ballots tab).",
 "Not a bug, and the site is honest about it. But it's the biggest gap in serving 'a wide range' of people: council candidates rarely publish, so this needs the automation work (party manifestos for local elections, council motions) to reach them."],
["Accessibility","Low","After the questions, the first page is 'Your area' (map, planning and petitions, around 850 words). The candidates are on step 4 of 4. For less confident users that's a lot to get through before seeing who is standing.",
 "Margaret, Brenda, Stan (low digital confidence).",
 "Result pages for every ballot persona.",
 "For Romily: consider landing on the candidates with the area steps one click away, or putting a clear 'See who is standing' button near the top (there is one; check it's prominent on mobile)."],
["Accessibility","Info","What went well: axe-core found no other WCAG 2.2 AA failures on the questions, area and candidates pages, in light or dark mode. No page scrolled sideways, even at 320 px wide. The whole journey could be done by keyboard alone. Answer buttons expose their pressed state. The estimated reading level of the main pages is roughly age 11–13 (Flesch-Kincaid grade 5–8).",
 "All.",
 "axe-core 4.x on 3 pages × 27 journeys; overflow and target-size checks; a simple Flesch-Kincaid estimate.",
 "Keep it that way. Reading levels are a rough guide only."],
["Accessibility","Info","The site is English only. Seven testers have another first language (Welsh, Gaelic, Polish, Arabic, Cantonese, Urdu, Yoruba). Barny's decision is not to translate. The pages declare en-GB, so browser translation will work.",
 "Dafydd, Morag, Tomasz, Fatima, Chen, Ayesha, Olu.",
 "Page metadata inLanguage en-GB; no language switcher.",
 "None needed now. Plain English helps most here."],
]
json.dump(F,open('findings.json','w'))
