# 30 fictional test people for What's It To Me?
# Wizard answers use the site's own labels. None = the person skips that question.
# yn keys: disability, carer, visa, benefits, drives, veteran  (True/False/None)
# access: how they use the web; drives which accessibility checks run for them.

P = [
 dict(id=1, name="Amara", about="19, first-year university student sharing a flat in King's Cross; works weekends in a café",
      postcode="WC1H 9JE", age="18 to 24", household="Housemates, or student halls", children="None",
      tenure="Rent privately", income="Under £15,000", work="Studying, with a part-time job", study="At university",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=False, veteran=False),
      access="mobile", first_language="English", confidence="high", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=2, name="Tomasz", about="41, electrician, self-employed, couple with two school-age children, mortgage, Kentish Town; Polish is his first language",
      postcode="NW5 2HS", age="35 to 49", household="A couple", children="School age", tenure="Own with a mortgage",
      income="£40,000 to £60,000", work="Self-employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="mobile", first_language="Polish", confidence="medium", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=3, name="Margaret", about="78, widow, owns her flat outright, Somers Town; macular degeneration, uses 200% zoom",
      postcode="NW1 1NN", age="65 or over", household="One adult", children="None", tenure="Own outright",
      income="£15,000 to £25,000", work="Retired", study="Not a student",
      yn=dict(disability=True, carer=False, visa=False, benefits=False, drives=False, veteran=False),
      access="zoom200", first_language="English", confidence="low", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=4, name="Yusuf", about="34, blind, uses a screen reader; lives alone in council flat in Kentish Town; employed part-time; on Universal Credit and PIP",
      postcode="NW1 9HX", age="25 to 34", household="One adult", children="None", tenure="Rent from a council",
      income="£15,000 to £25,000", work="Employed", study="Not a student",
      yn=dict(disability=True, carer=False, visa=False, benefits=True, drives=False, veteran=False),
      access="screen_reader", first_language="English", confidence="high", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=5, name="Grace", about="29, single mum of a toddler, council tenant, not working (caring for child), on Universal Credit",
      postcode="WC1H 9JE", age="25 to 34", household="One adult", children="Youngest under 5", tenure="Rent from a council",
      income="Under £15,000", work="Not working for another reason", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=True, drives=False, veteran=False),
      access="mobile_slow", first_language="English", confidence="medium", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=6, name="Rahul", about="52, consultant surgeon, couple, owns with mortgage, over £100k, Highgate — one street outside the by-election seat",
      postcode="N19 5DH", age="50 to 64", household="A couple", children="School age", tenure="Own with a mortgage",
      income="Over £100,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="desktop", first_language="English", confidence="high", expect=None),
 dict(id=7, name="Fatima", about="23, on a Graduate visa, shares a flat, looking for work",
      postcode="NW5 2HS", age="18 to 24", household="Housemates, or student halls", children="None", tenure="Rent privately",
      income="Under £15,000", work="Not working, looking for work", study="Not a student",
      yn=dict(disability=False, carer=False, visa=True, benefits=False, drives=False, veteran=False),
      access="mobile", first_language="Arabic", confidence="medium", expect="parl.holborn-and-st-pancras.by.2026-10-08"),
 dict(id=8, name="Dennis", about="67, Army veteran, lives with wife in housing-association home in Myatt's Fields; drives; limited mobility, keyboard only",
      postcode="SW9 7BD", age="65 or over", household="A couple", children="None", tenure="Rent from a council",
      income="£15,000 to £25,000", work="Retired", study="Not a student",
      yn=dict(disability=True, carer=True, visa=False, benefits=True, drives=True, veteran=True),
      access="keyboard", first_language="English", confidence="medium", expect="local.lambeth.myatts-fields.by.2026-10-08"),
 dict(id=9, name="Kezia", about="16, sixth-former in Myatt's Fields, lives with parents — can't vote in this council election, curious anyway",
      postcode="SW9 7BD", age="16 to 17", household="Other adults sharing", children="None", tenure="Other",
      income=None, work="Full-time student, not working", study="At school or college",
      yn=dict(disability=None, carer=None, visa=None, benefits=None, drives=None, veteran=None),
      access="mobile", first_language="English", confidence="high", expect="local.lambeth.myatts-fields.by.2026-10-08"),
 dict(id=10, name="Callum", about="45, farm worker near Drymen, couple with school-age kids, rents a tied cottage, drives",
      postcode="G63 0QP", age="35 to 49", household="A couple", children="School age", tenure="Rent privately",
      income="£25,000 to £40,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="mobile_slow", first_language="English", confidence="medium", expect="local.stirling.forth-and-endrick.by.2026-10-01"),
 dict(id=11, name="Shona", about="58, full-time unpaid carer for her adult son with a learning disability, Wick",
      postcode="KW1 5EA", age="50 to 64", household="Other adults sharing", children="Adult dependant", tenure="Rent from a council",
      income="Under £15,000", work="Not working for another reason", study="Not a student",
      yn=dict(disability=True, carer=True, visa=False, benefits=True, drives=True, veteran=False),
      access="desktop", first_language="English", confidence="low", expect="local.highland.wick-and-east-caithness.by.2026-10-01"),
 dict(id=12, name="Dafydd", about="71, retired teacher in Saron, first language Welsh, owns outright, drives",
      postcode="SA18 3UD", age="65 or over", household="A couple", children="None", tenure="Own outright",
      income="£25,000 to £40,000", work="Retired", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="desktop", first_language="Welsh", confidence="medium", expect="local.carmarthenshire.saron.by.2026-10-22"),
 dict(id=13, name="Priya", about="37, software developer in Aberdeen, couple, mortgage, £60-100k, one child under 5",
      postcode="AB15 5HH", age="35 to 49", household="A couple", children="Youngest under 5", tenure="Own with a mortgage",
      income="£60,000 to £100,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="dark", first_language="English", confidence="high", expect="local.aberdeen-city.midstocketrosemount.by.2026-10-08"),
 dict(id=14, name="Jordan", about="26, delivery rider in Blackpool, rents privately alone, zero-hours, on Universal Credit; dyslexic",
      postcode="FY1 2PU", age="25 to 34", household="One adult", children="None", tenure="Rent privately",
      income="Under £15,000", work="Self-employed", study="Not a student",
      yn=dict(disability=True, carer=False, visa=False, benefits=True, drives=False, veteran=False),
      access="dyslexia", first_language="English", confidence="medium", expect="local.blackpool.claremont.by.2026-10-01"),
 dict(id=15, name="Brenda", about="63, lives with husband in ex-mining village in Derbyshire, owns outright, husband has COPD",
      postcode="DE56 0AB", age="50 to 64", household="A couple", children="None", tenure="Own outright",
      income="£15,000 to £25,000", work="Not working for another reason", study="Not a student",
      yn=dict(disability=True, carer=True, visa=False, benefits=False, drives=True, veteran=False),
      access="low_confidence", first_language="English", confidence="low", expect="local.amber-valley.kilburn-denby-holbrook-horsley.by.2026-10-08"),
 dict(id=16, name="Kwame", about="31, nurse, couple, private renters in Newcastle-under-Lyme, one child at school",
      postcode="ST5 1PN", age="25 to 34", household="A couple", children="School age", tenure="Rent privately",
      income="£40,000 to £60,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="mobile", first_language="English", confidence="high", expect="local.newcastle-under-lyme.town.by.2026-10-08"),
 dict(id=17, name="Siobhan", about="44, lives in Belfast (no election there now) — tests the Northern Ireland path",
      postcode="BT7 1NN", age="35 to 49", household="One adult", children="School age", tenure="Rent privately",
      income="£25,000 to £40,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="desktop", first_language="English", confidence="high", expect=None),
 dict(id=18, name="Leo", about="22, trans man, apprentice in Manchester city centre, flat-share — no election in his area",
      postcode="M1 3BR", age="18 to 24", household="Housemates, or student halls", children="None", tenure="Rent privately",
      income="£15,000 to £25,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=False, veteran=False),
      access="mobile", first_language="English", confidence="high", expect=None),
 dict(id=19, name="Morag", about="81, crofter's widow in Stornoway, Gaelic speaker, very occasional internet user via tablet",
      postcode="HS1 2DA", age="65 or over", household="One adult", children="None", tenure="Own outright",
      income="Under £15,000", work="Retired", study="Not a student",
      yn=dict(disability=True, carer=False, visa=False, benefits=True, drives=False, veteran=False),
      access="tablet", first_language="Scottish Gaelic", confidence="low", expect=None),
 dict(id=20, name="Chen", about="48, restaurant owner in Hertford, self-employed, couple, mortgage, school-age kids",
      postcode="SG14 1QA", age="35 to 49", household="A couple", children="School age", tenure="Own with a mortgage",
      income="£60,000 to £100,000", work="Self-employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="desktop", first_language="Cantonese", confidence="medium", expect="local.east-hertfordshire.hertford-kingsmead.by.2026-10-22"),
 dict(id=21, name="Ayesha", about="39, Leeds, stay-at-home mum of three, couple, rents from housing association, husband a taxi driver",
      postcode="LS28 5PL", age="35 to 49", household="A couple", children="School age", tenure="Rent from a council",
      income="£25,000 to £40,000", work="Not working for another reason", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=True, drives=True, veteran=False),
      access="mobile", first_language="Urdu", confidence="medium", expect="local.leeds.calverley-farsley.by.2026-10-22"),
 dict(id=22, name="Gareth", about="55, redundant factory manager in Worksop (South East ward, no election — I first expected Worksop East; the site was right), looking for work, owns with mortgage, divorced",
      postcode="S80 2JJ", age="50 to 64", household="One adult", children="None", tenure="Own with a mortgage",
      income="Under £15,000", work="Not working, looking for work", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=True, drives=True, veteran=True),
      access="desktop", first_language="English", confidence="medium", expect=None),
 dict(id=23, name="Ellie", about="20, wheelchair user, university student in Salisbury area living with parents",
      postcode="SP1 2EW", age="18 to 24", household="Other adults sharing", children="None", tenure="Other",
      income="£40,000 to £60,000", work="Full-time student, not working", study="At university",
      yn=dict(disability=True, carer=False, visa=False, benefits=False, drives=False, veteran=False),
      access="mobile", first_language="English", confidence="high", expect="local.wiltshire.salisbury-milford.by.2026-10-15"),
 dict(id=24, name="Bernard", about="69, retired farmer near Bradninch, owns outright, over £100k from land rent; colour-blind",
      postcode="EX5 4QN", age="65 or over", household="A couple", children="None", tenure="Own outright",
      income="Over £100,000", work="Retired", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="colour_blind", first_language="English", confidence="medium", expect="local.mid-devon.bradninch.by.2026-10-15"),
 dict(id=25, name="Olu", about="35, asylum seeker in shared housing in Runcorn, not allowed to work",
      postcode="WA7 2RS", age="35 to 49", household="Other adults sharing", children="None", tenure="Other",
      income="Under £15,000", work="Not working for another reason", study="Not a student",
      yn=dict(disability=False, carer=False, visa=True, benefits=False, drives=False, veteran=False),
      access="mobile_small", first_language="Yoruba", confidence="medium", expect="local.halton.beechwood-heath.by.2026-10-29"),
 dict(id=26, name="Harriet", about="32, skips every optional question — privacy-minded; lives in Poole",
      postcode="BH14 0HA", age=None, household=None, children=None, tenure=None, income=None, work=None, study=None,
      yn=dict(disability=None, carer=None, visa=None, benefits=None, drives=None, veteran=None),
      access="desktop", first_language="English", confidence="high", expect="local.bournemouth-christchurch-and-poole.penn-hill.by.2026-11-05"),
 dict(id=27, name="Stan", about="74, lives alone in Amble, types his postcode in lower case with no space",
      postcode="ne650dr", age="65 or over", household="One adult", children="None", tenure="Rent from a council",
      income="Under £15,000", work="Retired", study="Not a student",
      yn=dict(disability=True, carer=False, visa=False, benefits=True, drives=False, veteran=True),
      access="low_confidence", first_language="English", confidence="low", expect="local.northumberland.amble.by.2026-10-01"),
 dict(id=28, name="Nadia", about="27, mistypes her postcode (a lower-case L instead of the number 1) then corrects it, Lochgilphead",
      postcode="PA31 8NB", typo="PA3l 8NB", age="25 to 34", household="A couple", children="Youngest under 5",
      tenure="Rent privately", income="£25,000 to £40,000", work="Employed", study="Not a student",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=True, veteran=False),
      access="mobile", first_language="English", confidence="medium", expect="local.argyll-and-bute.mid-argyll.by.2026-10-29"),
 dict(id=29, name="Rhys", about="24, Cardiff, student nurse, lives in halls — no election in his area; checks what Wales shows",
      postcode="CF10 1BD", age="18 to 24", household="Housemates, or student halls", children="None",
      tenure="University halls", income="Under £15,000", work="Full-time student, not working", study="At university",
      yn=dict(disability=False, carer=False, visa=False, benefits=False, drives=False, veteran=False),
      access="desktop", first_language="English", confidence="high", expect=None),
 dict(id=30, name="Beatrice", about="46, NHS manager in Grantham with a learning disability in the family; enters an outcode only",
      postcode="NG31", age="35 to 49", household="A couple", children="Adult dependant", tenure="Own with a mortgage",
      income="£40,000 to £60,000", work="Employed", study="Not a student",
      yn=dict(disability=True, carer=True, visa=False, benefits=False, drives=True, veteran=False),
      access="desktop", first_language="English", confidence="high", expect="local.south-kesteven.grantham-st-wulframs.by.2026-10-22"),
]
