insert into parties (ec_id,name,parent_party_ec_id) values ('PP63','Green Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP52','Conservative and Unionist Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP7931','Reform UK',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP90','Liberal Democrats',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('joint-party:53-119','Labour and Co-operative Party','PP53') on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP53','Labour Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP6810','the Borough first Independents',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('ynmp-party:2','Independent',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP18382','Restore Britain',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP130','Scottish Green Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP102','Scottish National Party (SNP)',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP79','Christian Peoples Alliance',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP110','The Socialist Party of Great Britain',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP66','The Official Monster Raving Loony Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP12958','Climate Party',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP11382','Workers Party of Britain',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP11423','Rejoin EU',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP9053','UK Voice',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP12791','Communist League Election Campaign',NULL) on conflict (ec_id) do nothing;
insert into parties (ec_id,name,parent_party_ec_id) values ('PP85','UK Independence Party (UKIP)',NULL) on conflict (ec_id) do nothing;